apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: alertmanager
spec:
  components:
    - name: alertmanager-conf
      type: k8s-objects
      properties:
        objects:
        - apiVersion: v1
          kind: ConfigMap
          metadata:
            name: alertmanager-conf
          data:
            alertmanager.yml: |
              global: {}
              receivers:
              - name: default-receiver
              route:
                group_interval: 5m
                group_wait: 15s
                receiver: default-receiver
                repeat_interval: 1h
              templates:
              - /etc/alertmanager/*.tmpl
    - name: alertmanager
      type: webservice
      properties:
        image: bitnami/alertmanager:0.24.0
        imagePullPolicy: IfNotPresent
        labels:
          "app.kubernetes.io/name": alertmanager
          "prometheus.io/scrape": "true"
        ports:
        - name: http
          port: 9093
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 9093
        readinessProbe:
          httpGet:
            path: /
            port: 9093
        volumeMounts:
          configMap:
          - name: alertmanager-conf
            mountPath: /etc/alertmanager
            cmName: alertmanager-conf
      traits:
      - type: command
        properties:
          args:
          - --storage.path=/alertmanager
          - --config.file=/etc/alertmanager/alertmanager.yml
      - type: resource
        properties:
          cpu: 0.5
          memory: "512Mi"
      - type: expose
        properties:
          port: [9093]
          annotations:
            "prometheus.io/port":   "9093"
            "prometheus.io/scrape": "true"
            "prometheus.io/path":   "/metrics"
      - type: storage
        properties:
          pvc:
          - name: alertmanager-data
            mountPath: /alertmanager
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: "50Mi"