apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: crane-sample
spec:
  components:
    - name: crane-nginx
      type: webservice
      properties:
        image: nginx:1.14.2
        ports:
         - port: 80
           expose: true
      traits:
        # effective-hpa enables prediction-driven autoscaling and helps you manage application scaling in an easy way
        - type: effective-hpa
        # resource-analytics gives you recommended values for resources in a cluster and use them to improve the resource utilization of the cluster.
        - type: resource-analytics
          properties:
            analyzePeriod: 30
